sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: JHQnhbcTRooxg/GdiHmS64Jx+7LAKKotN/usKsJSE3teoTLg9X9/mJysUqitpJI+2o1T8TdSdD2pHeypkKM3qNnPeuYxlJbxF3C3MmV4ALOivMbg+insPXsIcjq2Zwegqmtab1vN4qTz+PVKPpbILbDHwPa7rlwgQ3ZTxYeK7jBGJFcl95TjHQNDFkbmuEvUioXPq/24fNvJAAhybELxRLGrCAXWtnWaF8/SBaXBWdVHf3qnv06iTj5oEKgxjRAob78zQzR87zHDPgHBZn/GrblXREZyNw5J7Nh5wx3iBpZYu2axOOduBzDTGjV+iv9rjwUVAYYTzHHw+VuLE0MXqYkt/xFv15vqYw5U3mD1Bw36nt+QL/dj7EhccRqzD27fPHiIfCrII6KokvmBGFKVGbAYzpVesAcoJMe+jRx4YBPmtCqG9mIovGY0fuW/+drzgLWyFcX+kN0Hhel+Fgz+6jzg8Sf7ZF60PxtajLaXdH+Wdn8bqcdzjF3ZrWDGbcJSs5mRo9ev+jywnOiegUDOL/6UqwRo2W2zdFWcHYmWs9FKVwatqe8Wy9Fs8QVFj7QVx+1EUyds7xqQfu5S92UQ4gCUsbTv8qEkPjdEEd+yFyrnkdE8JA4cXFPRmaHC/Z+dD4pOqro/29fzwyqvFMMilLpwoV3K80/yHJvSOXjrCkY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Nan-Sherwood-at-Pine-Camp--Or-The-Old-Lumberman-s-Secret_2691
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy